# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  - name: nom
    value: EasyTest
  - name: testeur
    value: MouhcineHK

stages:
- stage: Build
  displayName: 'Mon premier stage'
  jobs:
  - job: BuildJob
    displayName: 'Mon premier job'
    steps:
    - script: echo $(nom) !
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'

- stage: 
  displayName: 'Mon second stage'
  jobs:
  - job: BuildJob
    displayName: 'Mon second job'
    steps:
    - script: echo Hello $(testeur)!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'